export const fallbackListings = [
  {
    _id: '1',
    title: 'Sea Glass House',
    description:
      'A bright coastal retreat with quiet mornings, open skies, and room to gather.',
    category: 'Beaches',
    price: 5200,
    location: 'Candolim, Goa',
    country: 'India',
    image: {
      url: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1000&q=85',
    },
    owner: { username: 'maya' },
    reviews: [
      {
        rating: 5,
        comment: 'A beautiful, restful stay.',
        author: { username: 'ravi' },
        createdAt: '2025-03-01',
      },
    ],
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathroom: 2,
    checkin: '14:00',
    checkout: '11:00',
    usp1: 'Steps from the beach',
    usp2: 'Sunset terrace',
    usp3: 'Fast Wi-Fi',
  },
  {
    _id: '2',
    title: 'Alpine Window',
    description:
      'A warm mountain cabin for slow days, long walks, and stargazing after dinner.',
    category: 'Mountains',
    price: 6800,
    location: 'Manali, Himachal Pradesh',
    country: 'India',
    image: {
      url: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1000&q=85',
    },
    owner: { username: 'arjun' },
    reviews: [],
    guests: 6,
    bedrooms: 3,
    beds: 4,
    bathroom: 2,
    checkin: '13:00',
    checkout: '10:00',
    usp1: 'Valley views',
    usp2: 'Wood-burning stove',
    usp3: 'Private balcony',
  },
  {
    _id: '3',
    title: 'The Indigo Courtyard',
    description:
      'A characterful city home where old-world detail meets a calm modern interior.',
    category: 'Heritage',
    price: 4300,
    location: 'Jaipur, Rajasthan',
    country: 'India',
    image: {
      url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85',
    },
    owner: { username: 'nisha' },
    reviews: [
      {
        rating: 4,
        comment: 'Full of charm and thoughtful touches.',
        author: { username: 'zoya' },
        createdAt: '2025-06-01',
      },
    ],
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathroom: 1,
    checkin: '15:00',
    checkout: '11:00',
    usp1: 'Historic neighborhood',
    usp2: 'Private courtyard',
    usp3: 'Breakfast included',
  },
  {
    _id: '4',
    title: 'Palm & Plunge',
    description:
      'A private pool villa wrapped in greenery, made for unhurried afternoons.',
    category: 'Pools',
    price: 9200,
    location: 'Alibaug, Maharashtra',
    country: 'India',
    image: {
      url: 'https://images.unsplash.com/photo-1582610116397-edb318620f90?auto=format&fit=crop&w=1000&q=85',
    },
    owner: { username: 'dev' },
    reviews: [],
    guests: 8,
    bedrooms: 4,
    beds: 5,
    bathroom: 4,
    checkin: '14:00',
    checkout: '11:00',
    usp1: 'Private swimming pool',
    usp2: 'Chef on request',
    usp3: 'Garden dining',
  },
]
